const API='https://sanci9517-twitch-api.sandor-bogadi95.workers.dev';
const NAV=[['index.html','Főoldal','⌂'],['twitch.html','Twitch','●'],['games.html','Játékok','◈'],['menetrend.html','Menetrend','◷'],['clips.html','Clips','▶'],['hirek.html','Hírek','✦'],['stats.html','Statisztika','▥'],['milestones.html','Célok','↗'],['discord.html','Közösség','♧'],['tamogatas.html','Támogatás','♥'],['kapcsolat.html','Kapcsolat','✉']];
const DEF={brand:'SANCI9517',tagline:'Játék. Stream. Közösség.',intro:'Fortnite, Hearthstone és közösségi tartalom egy helyen.',heroButtons:[],social:{},manualLive:{enabled:false,live:false,game:'Fortnite',title:'Következő stream hamarosan',viewers:0},nextStream:{},games:[],schedule:[],news:[],clips:[],milestone:{current:0,target:5000},design:{}};
let cfg=DEF, twitchData=null;
async function loadConfig(){try{const r=await fetch('config.json?v='+Date.now());cfg=merge(DEF,await r.json())}catch{cfg=DEF}try{const local=JSON.parse(localStorage.getItem('sanci_site_config')||'null');if(local)cfg=merge(cfg,local)}catch{}}
function merge(a,b){const o={...a,...b};for(const k of ['social','manualLive','nextStream','milestone','design'])o[k]={...(a[k]||{}),...(b[k]||{})};return o}
function esc(x=''){return String(x).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[m]))}
function shell(){const file=location.pathname.split('/').pop()||'index.html';document.body.innerHTML=`<header class="top"><a class="brand" href="index.html"><span class="logo">S</span><span><b>${esc(cfg.brand)}</b><small>STREAM • COMMUNITY</small></span></a><nav class="desktop">${NAV.slice(0,6).map(n=>`<a class="${file===n[0]?'active':''}" href="${n[0]}">${n[2]} ${n[1]}</a>`).join('')}</nav><button class="menu-btn" id="menuBtn">☰</button></header><div class="overlay" id="overlay"><aside class="drawer"><div class="drawer-head"><b>${esc(cfg.brand)}</b><button id="close">×</button></div><div class="drawer-grid">${NAV.map(n=>`<a class="${file===n[0]?'active':''}" href="${n[0]}"><i>${n[2]}</i>${n[1]}</a>`).join('')}<a class="admin-link" href="admin.html"><i>⚙</i>Admin</a></div></aside></div><main id="page"></main><footer><div><b>${esc(cfg.brand)}</b><p>${esc(cfg.intro)}</p></div><div class="foot-links">${Object.entries(cfg.social).filter(([,v])=>v).map(([k,v])=>`<a href="${esc(v)}" target="_blank" rel="noopener">${k}</a>`).join('')}</div><small>© ${new Date().getFullYear()} SANCI9517</small></footer>`;document.getElementById('menuBtn').onclick=()=>document.getElementById('overlay').classList.add('open');document.getElementById('close').onclick=()=>document.getElementById('overlay').classList.remove('open');document.getElementById('overlay').onclick=e=>{if(e.target.id==='overlay')e.currentTarget.classList.remove('open')}}
async function twitch(){try{const r=await fetch(API+'/twitch/stats',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();twitchData={...d,source:'twitch'};return twitchData}catch{const m=cfg.manualLive||{};return twitchData={live:!!m.live,game_name:m.game||'—',title:m.title||'',viewers:Number(m.viewers||0),followers:null,source:'manual'}}}
function liveCard(d){return `<div class="live-card ${d.live?'is-live':''}"><span class="live-dot"></span><div><b>${d.live?'ÉLŐ ADÁS':'OFFLINE'}</b><strong>${esc(d.game_name||'—')}</strong><small>${esc(d.title|| (d.live?'Most élőben a csatornán.': 'A következő stream hamarosan.'))}</small></div>${d.live&&d.viewers!=null?`<em>${Number(d.viewers).toLocaleString('hu-HU')} néző</em>`:''}</div>`}
function btns(){return (cfg.heroButtons||[]).map(x=>`<a class="btn ${x.primary?'primary':''}" href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.label)}</a>`).join('')}
async function renderHome(){const d=await twitch();const n=cfg.nextStream||{};document.getElementById('page').innerHTML=`<section class="hero"><div><span class="eyebrow">SANCI9517 • CREATOR HUB</span><h1>${esc(cfg.tagline)}</h1><p>${esc(cfg.intro)}</p><div class="actions">${btns()}</div></div>${liveCard(d)}</section><section class="section"><div class="section-head"><span class="eyebrow">MOST NÉZD</span><h2>Élő állapot egy pillantásra</h2></div><div class="feature-grid"><a class="feature accent" href="twitch.html"><small>TWITCH</small><h3>${d.live?'🔴 Élőben vagyok':'⚫ Most offline'}</h3><p>${esc(d.game_name||'—')} ${d.live?'• '+Number(d.viewers||0).toLocaleString('hu-HU')+' néző':''}</p></a><a class="feature" href="menetrend.html"><small>KÖVETKEZŐ STREAM</small><h3>${esc(n.day||n.date||'Hamarosan')}</h3><p>${esc(n.time||'')} ${n.game?'• '+esc(n.game):''}</p></a><a class="feature" href="discord.html"><small>KÖZÖSSÉG</small><h3>Csatlakozz</h3><p>Discord, TikTok, YouTube és Twitch egy helyen.</p></a></div></section><section class="section"><div class="section-head"><span class="eyebrow">TARTALOM</span><h2>Játékok és frissítések</h2></div><div class="card-grid">${cfg.games.filter(x=>x.active!==false).map(g=>`<a class="card" href="games.html"><span class="icon">◈</span><h3>${esc(g.name)}</h3><p>${esc(g.description)}</p></a>`).join('')}${(cfg.news||[]).filter(x=>x.active!==false).slice(0,2).map(x=>`<a class="card" href="hirek.html"><span class="icon">✦</span><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p></a>`).join('')}</div></section><section class="goal"><div><span class="eyebrow">KÖZÖS CÉL</span><h2>${esc(cfg.milestone.label||'Következő cél')}</h2><p>${esc(cfg.milestone.description||'')}</p></div><div class="progress"><b>${Number(cfg.milestone.current||0).toLocaleString('hu-HU')} / ${Number(cfg.milestone.target||0).toLocaleString('hu-HU')}</b><span><i style="width:${Math.min(100,Number(cfg.milestone.current||0)/Math.max(1,Number(cfg.milestone.target||1))*100)}%"></i></span></div></section>`}
function page(title,sub,body){document.getElementById('page').innerHTML=`<section class="page-title"><span class="eyebrow">SANCI9517</span><h1>${esc(title)}</h1><p>${esc(sub)}</p></section>${body}`}
async function render(){await loadConfig();shell();const f=location.pathname.split('/').pop()||'index.html';if(f==='index.html')return renderHome();if(f==='twitch.html'){const d=await twitch();return page('Twitch','Élő állapot, csatorna és közvetlen elérés.',`${liveCard(d)}<section class="panel-grid"><div class="panel"><small>KÖVETŐK</small><strong>${d.followers==null?'—':Number(d.followers).toLocaleString('hu-HU')}</strong></div><div class="panel"><small>NÉZŐK</small><strong>${d.live?Number(d.viewers||0).toLocaleString('hu-HU'):'0'}</strong></div><div class="panel"><small>JÁTÉK</small><strong>${esc(d.game_name||'—')}</strong></div></section><div class="actions"><a class="btn primary" href="${cfg.social.twitch||'https://www.twitch.tv/sanci9517'}" target="_blank">Twitch megnyitása</a></div>`)}
if(f==='games.html')return page('Játékok','A jelenlegi és tervezett stream játékok.',`<div class="card-grid">${cfg.games.map(g=>`<article class="card ${g.active===false?'muted-card':''}"><span class="icon">◈</span><h3>${esc(g.name)}</h3><p>${esc(g.description)}</p></article>`).join('')}</div>`);
if(f==='menetrend.html')return page('Menetrend','A stream időpontjai. A változtatásokat az Admin oldalon kezelheted.',`<div class="schedule">${cfg.schedule.filter(x=>x.active!==false).map(x=>`<div><b>${esc(x.day)}</b><strong>${esc(x.time)}</strong><span>${esc(x.game)}</span><small>${esc(x.title)}</small></div>`).join('')}</div>`);
if(f==='clips.html')return page('Clips','Kiemelt videók és rövid tartalmak.',`<div class="card-grid">${cfg.clips.length?cfg.clips.map(x=>`<a class="card" href="${esc(x.url)}" target="_blank"><span class="icon">▶</span><h3>${esc(x.title)}</h3><p>Klip megnyitása</p></a>`).join(''):'<div class="empty">Még nincs kiemelt clip. Az Admin oldalon hozzáadhatod.</div>'}</div>`);
if(f==='hirek.html')return page('Hírek','Újdonságok a csatornáról és a közösségről.',`<div class="news">${cfg.news.filter(x=>x.active!==false).map(x=>`<article><small>${esc(x.date)}</small><h2>${esc(x.title)}</h2><p>${esc(x.body)}</p></article>`).join('')||'<div class="empty">Még nincs hír.</div>'}</div>`);
if(f==='stats.html'){const d=await twitch();return page('Statisztika','Twitch adatok automatikusan, kapcsolat hiányában kézi tartalék móddal.',`<div class="panel-grid"><div class="panel"><small>KÖVETŐK</small><strong>${d.followers==null?'—':Number(d.followers).toLocaleString('hu-HU')}</strong></div><div class="panel"><small>ÉLŐ NÉZŐK</small><strong>${Number(d.viewers||0).toLocaleString('hu-HU')}</strong></div><div class="panel"><small>JÁTÉK</small><strong>${esc(d.game_name||'—')}</strong></div><div class="panel"><small>FORRÁS</small><strong>${d.source==='twitch'?'Twitch API':'Admin'}</strong></div></div>`)}
if(f==='milestones.html')return page('Célok','Közös mérföldkövek.',`<section class="goal"><div><span class="eyebrow">MÉRFÖLDKŐ</span><h2>${esc(cfg.milestone.label||'Cél')}</h2><p>${esc(cfg.milestone.description||'')}</p></div><div class="progress"><b>${Number(cfg.milestone.current||0).toLocaleString('hu-HU')} / ${Number(cfg.milestone.target||0).toLocaleString('hu-HU')}</b><span><i style="width:${Math.min(100,Number(cfg.milestone.current||0)/Math.max(1,Number(cfg.milestone.target||1))*100)}%"></i></span></div></section>`);
if(f==='discord.html')return page('Közösség','Minden fontos közösségi felület egy helyen.',`<div class="social-grid">${Object.entries(cfg.social).filter(([,v])=>v).map(([k,v])=>`<a class="card" href="${esc(v)}" target="_blank"><span class="icon">↗</span><h3>${k}</h3><p>Megnyitás</p></a>`).join('')}</div>`);
if(f==='tamogatas.html')return page('Támogatás','Ha szeretnéd támogatni a tartalmakat, itt találod a lehetőségeket.',`<div class="panel accent"><h2>Köszönöm a támogatást!</h2><p>A támogatási linkeket az Admin oldalon tudod beállítani.</p></div>`);
if(f==='kapcsolat.html')return page('Kapcsolat','Üzleti és együttműködési megkeresésekhez.',`<div class="panel"><h2>Kapcsolat</h2><p>Az elérhetőségeket az Admin oldalon tudod kezelni.</p><div class="actions">${cfg.social.youtube?`<a class="btn" href="${esc(cfg.social.youtube)}" target="_blank">YouTube</a>`:''}${cfg.social.twitch?`<a class="btn" href="${esc(cfg.social.twitch)}" target="_blank">Twitch</a>`:''}</div></div>`)}
render();
