const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type,Authorization"};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...CORS,"Content-Type":"application/json"}})}
function id(){return crypto.randomUUID()}
async function hash(value){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function current(env){const poll=await env.DB.prepare("SELECT id,question,active,created_at,ended_at FROM polls WHERE active=1 ORDER BY created_at DESC LIMIT 1").first();if(!poll)return {active:false,options:[]};const {results}=await env.DB.prepare("SELECT o.id,o.label,o.description,o.icon,COUNT(v.id) votes FROM poll_options o LEFT JOIN votes v ON v.option_id=o.id WHERE o.poll_id=? GROUP BY o.id ORDER BY o.sort_order").bind(poll.id).all();return {active:true,id:poll.id,question:poll.question,created_at:poll.created_at,options:results}}
function authorized(request,env){const h=request.headers.get('Authorization')||'';return h===`Bearer ${env.POLL_ADMIN_TOKEN}`}
async function vote(request,env){let body;try{body=await request.json()}catch{return json({error:'Érvénytelen kérés.'},400)}if(!body.optionId||!body.voterId)return json({error:'Hiányzó adatok.'},400);const poll=await env.DB.prepare("SELECT id FROM polls WHERE active=1 LIMIT 1").first();if(!poll)return json({error:'Nincs aktív szavazás.'},409);const voter=await hash(String(body.voterId));const option=await env.DB.prepare("SELECT id FROM poll_options WHERE id=? AND poll_id=?").bind(body.optionId,poll.id).first();if(!option)return json({error:'Érvénytelen választás.'},400);try{await env.DB.prepare("INSERT INTO votes(id,poll_id,option_id,voter_hash,created_at) VALUES(?,?,?,?,datetime('now'))").bind(id(),poll.id,option.id,voter).run()}catch(e){if(String(e).toLowerCase().includes('unique'))return json({error:'already voted'},409);throw e}return json({ok:true})}
async function admin(request,env){if(!authorized(request,env))return json({error:'Hozzáférés megtagadva.'},401);let body;try{body=await request.json()}catch{return json({error:'Érvénytelen kérés.'},400)}if(!body.question||!Array.isArray(body.options)||!body.options.length)return json({error:'Hiányzó szavazás adatok.'},400);const pollId=id();const options=body.options.map((o,i)=>({id:id(),label:String(o.label||'').trim(),description:String(o.description||''),icon:String(o.icon||'🎮'),sort:i})).filter(o=>o.label);if(!options.length)return json({error:'Legalább egy válasz szükséges.'},400);await env.DB.prepare("UPDATE polls SET active=0,ended_at=datetime('now') WHERE active=1").run();await env.DB.prepare("INSERT INTO polls(id,question,active,created_at) VALUES(?,?,1,datetime('now'))").bind(pollId,String(body.question).trim()).run();for(const o of options)await env.DB.prepare("INSERT INTO poll_options(id,poll_id,label,description,icon,sort_order) VALUES(?,?,?,?,?,?)").bind(o.id,pollId,o.label,o.description,o.icon,o.sort).run();return json({ok:true,id:pollId})}
export default{async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});const url=new URL(request.url);try{if(url.pathname==='/poll/current'&&request.method==='GET')return json(await current(env));if(url.pathname==='/poll/vote'&&request.method==='POST')return vote(request,env);if(url.pathname==='/poll/admin'&&request.method==='POST')return admin(request,env);if(url.pathname==='/poll/health')return json({ok:true});return json({error:'Not found'},404)}catch(e){console.error(e);return json({error:'Szerverhiba.'},500)}}};
