import { navigate } from '../../core/router.js';
import { getSite, saveSiteSettings } from '../../core/site-state.js';
import { getNavigation, saveNavigation } from '../../core/navigation-state.js';
import { getPages, getPageById, savePages, syncPagesFromNavigation } from '../../core/page-state.js';

const ELEMENT_TYPES = ['text', 'game', 'twitch', 'image', 'link', 'stats'];

export function renderWebsiteAdmin(root) {
  const currentSite = getSite(); const items = normalizeItems(getNavigation()); const pages = getPages(); const selectedPage = pages[0] || null;
  root.innerHTML = `<div class="admin-page"><header class="admin-header"><div><span class="admin-kicker">Weboldal</span><h1>Weboldal kezelése</h1><p>Alapadatok, oldalak és menüpontok kezelése.</p></div><button class="button button-secondary" type="button" data-admin-back>Vissza</button></header><main class="admin-content admin-editor-layout"><section class="admin-card admin-editor-card"><span class="admin-card-label">Alapadatok</span><h2>Weboldal adatai</h2><p class="admin-help">Ezek az adatok jelennek meg a weboldal központi részein.</p><form class="admin-site-form" data-site-form><label class="admin-form-field"><span>Weboldal neve</span><input name="brand" value="${escapeHtml(currentSite.brand)}" maxlength="80" required></label><label class="admin-form-field"><span>Leírás</span><textarea name="description" rows="3" maxlength="240">${escapeHtml(currentSite.description)}</textarea></label><button class="button button-primary" type="submit">Weboldal adatai mentése</button><span class="admin-form-status" data-site-save-status></span></form></section><section class="admin-card admin-editor-card"><span class="admin-card-label">Oldalak</span><h2>Oldal tartalmának szerkesztése</h2><p class="admin-help">Egy boxon belül több különböző elemet is elhelyezhetsz.</p><form class="admin-page-form" data-page-form>${renderPageForm(selectedPage, pages)}</form></section><section class="admin-card admin-editor-card"><div class="admin-card-heading"><div><span class="admin-card-label">Navigáció</span><h2>Menüpontok</h2></div><button class="button button-secondary" type="button" data-add-item>+ Új menüpont</button></div><p class="admin-help">Állítsd be a menüpont nevét, típusát, helyét és láthatóságát.</p><div class="admin-nav-editor" data-nav-editor>${items.map((item,index)=>renderItem(item,index)).join('')}</div><div class="admin-form-meta"><span>Menüpontok: <strong data-item-count>${items.length}</strong></span><span data-nav-save-status></span></div><button class="button button-primary" type="button" data-save-navigation>Menüpontok mentése</button></section></main></div>`;
  root.querySelector('[data-admin-back]')?.addEventListener('click',()=>navigate('/admin'));
  root.querySelector('[data-site-form]')?.addEventListener('submit',(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);const saved=saveSiteSettings({brand:String(data.get('brand')||'').trim(),description:String(data.get('description')||'').trim()});const status=root.querySelector('[data-site-save-status]');if(status)status.textContent=saved?'Mentve ✓':'Mentés sikertelen';});
  bindPageEditor(root);
  root.querySelector('[data-add-item]')?.addEventListener('click',()=>{const editor=root.querySelector('[data-nav-editor]');if(!editor)return;const index=editor.querySelectorAll('[data-nav-item]').length;editor.insertAdjacentHTML('beforeend',renderItem({label:'Új menüpont',path:'/uj-oldal',type:'route',enabled:true},index));bindEditor(root);updateCount(root);});
  bindEditor(root);
}

function bindPageEditor(root){const form=root.querySelector('[data-page-form]');if(!form)return;const select=form.querySelector('[data-page-select]');if(select&&select.dataset.bound!=='true'){select.dataset.bound='true';select.addEventListener('change',(event)=>{const page=getPageById(event.target.value);form.innerHTML=renderPageForm(page,getPages());bindPageEditor(root);});}form.querySelector('[data-add-block]')?.addEventListener('click',()=>{const list=form.querySelector('[data-block-list]');if(!list)return;list.insertAdjacentHTML('beforeend',renderBlockForm({id:createBlockId(),type:'text',title:'Új box',content:'',elements:[]},list.children.length));bindBlockControls(form);});bindBlockControls(form);if(form.dataset.submitBound==='true')return;form.dataset.submitBound='true';form.addEventListener('submit',(event)=>{event.preventDefault();const data=new FormData(form);const id=String(data.get('id')||'');const currentPages=getPages();const index=currentPages.findIndex(page=>page.id===id);if(index<0)return;const blocks=[...form.querySelectorAll('[data-block]')].map((box)=>{const type=ELEMENT_TYPES.includes(box.querySelector('[name="block-type"]')?.value)?box.querySelector('[name="block-type"]').value:'text';const title=box.querySelector('[name="block-title"]')?.value.trim()||'Box';const content=box.querySelector('[name="block-content"]')?.value.trim()||'';const elements=[...box.querySelectorAll('[data-element]')].map(readElement);return{id:box.dataset.block,type,title,content,elements:elements.length?elements:[{id:createElementId(),type,title,content}]};});currentPages[index]={...currentPages[index],title:String(data.get('title')||'').trim()||currentPages[index].title,content:String(data.get('content')||'').trim(),blocks};const status=form.querySelector('[data-page-save-status]');if(savePages(currentPages)){if(status)status.textContent='Mentve ✓';}else if(status)status.textContent='Mentés sikertelen';});}

function renderPageForm(page,pages){if(!page)return '<p class="admin-help">Még nincs létrehozott oldal. Hozz létre egy „Oldal” típusú menüpontot, majd mentsd el.</p>';const blocks=Array.isArray(page.blocks)?page.blocks:[];return `<label class="admin-form-field"><span>Oldal</span><select name="id" data-page-select>${pages.map(item=>`<option value="${escapeHtml(item.id)}" ${item.id===page.id?'selected':''}>${escapeHtml(item.title)}</option>`).join('')}</select></label><label class="admin-form-field"><span>Oldal címe</span><input name="title" value="${escapeHtml(page.title||'')}" maxlength="100" required></label><label class="admin-form-field"><span>Oldal szövege</span><textarea name="content" rows="6" maxlength="5000" placeholder="Ide írd az oldal fő szövegét...">${escapeHtml(page.content||'')}</textarea></label><div class="admin-block-editor"><div class="admin-card-heading"><div><span class="admin-card-label">Tartalmi boxok</span><h3>Boxok az oldalon</h3></div><button class="button button-secondary" type="button" data-add-block>+ Box hozzáadása</button></div><p class="admin-help">Egy boxon belül több elem lehet: például kép + szöveg + gomb + Twitch.</p><div class="admin-block-list" data-block-list>${blocks.map(renderBlockForm).join('')}</div></div><div class="admin-form-meta"><span>Elérés: <strong>${escapeHtml(page.path||'/')}</strong></span><span data-page-save-status></span></div><button class="button button-primary" type="submit">Oldal mentése</button>`;}

function renderBlockForm(block,index){const type=ELEMENT_TYPES.includes(block?.type)?block.type:'text';const elements=Array.isArray(block?.elements)&&block.elements.length?block.elements:[{id:createElementId(),type,title:block?.title||'',content:block?.content||''}];return `<article class="admin-block-item" data-block="${escapeHtml(block.id)}"><div class="admin-block-item-top"><strong class="admin-block-number">Box ${index+1}</strong><div class="admin-block-actions"><button class="button button-secondary" type="button" data-block-up>↑ Fel</button><button class="button button-secondary" type="button" data-block-down>↓ Le</button><button class="button button-secondary" type="button" data-delete-block>Box törlése</button></div></div><label class="admin-form-field"><span>Alapértelmezett box típus</span><select name="block-type">${ELEMENT_TYPES.map((t)=>`<option value="${t}" ${t===type?'selected':''}>${typeLabel(t)}</option>`).join('')}</select></label><label class="admin-form-field"><span>Box címe</span><input name="block-title" value="${escapeHtml(block.title||'')}" maxlength="100" placeholder="Pl. Legutóbbi adás"></label><label class="admin-form-field"><span>Régi box tartalma</span><textarea name="block-content" rows="3" maxlength="2000">${escapeHtml(block.content||'')}</textarea></label><div class="admin-block-elements"><div class="admin-card-heading"><div><span class="admin-card-label">Box elemei</span><h4>Több elem egy boxban</h4></div><button class="button button-secondary" type="button" data-add-element>+ Elem hozzáadása</button></div><div data-element-list>${elements.map(renderElementForm).join('')}</div></div></article>`;}

function renderElementForm(element){const type=ELEMENT_TYPES.includes(element?.type)?element.type:'text';const id=element?.id||createElementId();return `<div class="admin-block-element" data-element="${escapeHtml(id)}"><div class="admin-block-item-top"><strong>Elem</strong><div class="admin-block-actions"><button class="button button-secondary" type="button" data-element-up>↑</button><button class="button button-secondary" type="button" data-element-down>↓</button><button class="button button-secondary" type="button" data-delete-element>Törlés</button></div></div><label class="admin-form-field"><span>Elem típusa</span><select name="element-type">${ELEMENT_TYPES.map((t)=>`<option value="${t}" ${t===type?'selected':''}>${typeLabel(t)}</option>`).join('')}</select></label><label class="admin-form-field"><span>Elem címe</span><input name="element-title" value="${escapeHtml(element.title||'')}" maxlength="100" placeholder="Elem címe"></label><label class="admin-form-field"><span>Elem tartalma</span><textarea name="element-content" rows="3" maxlength="2000" placeholder="Szöveg, kép URL, link vagy adat...">${escapeHtml(element.content||'')}</textarea></label></div>`;}
function readElement(element){const select=element.querySelector('[name="element-type"]');return{id:element.dataset.element||createElementId(),type:ELEMENT_TYPES.includes(select?.value)?select.value:'text',title:element.querySelector('[name="element-title"]')?.value.trim()||'',content:element.querySelector('[name="element-content"]')?.value.trim()||''};}
function typeLabel(type){return({text:'📝 Szöveg',game:'🎮 Játék',twitch:'📺 Twitch / stream',image:'🖼️ Kép',link:'🔗 Link / gomb',stats:'📊 Statisztika'})[type]||'📝 Szöveg';}

function bindBlockControls(form){form.querySelectorAll('[data-delete-block],[data-block-up],[data-block-down],[data-add-element],[data-delete-element],[data-element-up],[data-element-down]').forEach((button)=>{if(button.dataset.bound==='true')return;button.dataset.bound='true';button.addEventListener('click',()=>{const block=button.closest('[data-block]');if(!block)return;if(button.hasAttribute('data-delete-block')){block.remove();updateBlockNumbers(form);return;}if(button.hasAttribute('data-add-element')){const list=block.querySelector('[data-element-list]');if(list)list.insertAdjacentHTML('beforeend',renderElementForm({id:createElementId(),type:'text',title:'',content:''}));bindBlockControls(form);return;}const element=button.closest('[data-element]');if(element){const list=element.parentElement;if(button.hasAttribute('data-delete-element'))element.remove();else{const all=[...list.querySelectorAll('[data-element]')];const i=all.indexOf(element);const target=button.hasAttribute('data-element-up')?all[i-1]:all[i+1];if(target)button.hasAttribute('data-element-up')?target.before(element):target.after(element);}return;}const list=form.querySelector('[data-block-list]');if(!list)return;const all=[...list.querySelectorAll('[data-block]')];const i=all.indexOf(block);const target=button.hasAttribute('data-block-up')?all[i-1]:all[i+1];if(target)button.hasAttribute('data-block-up')?target.before(block):target.after(block);updateBlockNumbers(form);});});}
function updateBlockNumbers(form){form.querySelectorAll('[data-block]').forEach((block,index)=>{const n=block.querySelector('.admin-block-number');if(n)n.textContent=`Box ${index+1}`;});}
function createBlockId(){return `block-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;}
function createElementId(){return `element-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;}
function bindEditor(root){root.querySelectorAll('[data-nav-item]').forEach((row)=>{if(row.dataset.bound==='true')return;row.dataset.bound='true';row.querySelector('[data-type]')?.addEventListener('change',(event)=>updateTypeFields(row,event.target.value));row.querySelector('[name="label"]')?.addEventListener('input',(event)=>{const path=row.querySelector('[name="path"]');if(row.querySelector('[data-type]')?.value!=='external'&&path&&!path.dataset.userEdited)path.value=`/${createSlug(event.target.value)}`;});row.querySelector('[name="path"]')?.addEventListener('input',(event)=>{event.target.dataset.userEdited='true';});row.querySelector('[data-up]')?.addEventListener('click',()=>moveItem(row,-1,root));row.querySelector('[data-down]')?.addEventListener('click',()=>moveItem(row,1,root));row.querySelector('[data-delete]')?.addEventListener('click',()=>{row.remove();updateCount(root);});updateTypeFields(row,row.querySelector('[data-type]')?.value||'route');});const saveButton=root.querySelector('[data-save-navigation]');if(saveButton?.dataset.bound!=='true'){saveButton.dataset.bound='true';saveButton.addEventListener('click',saveNavigationFromForm);}}
function updateTypeFields(row,type){const external=type==='external';const route=row.querySelector('[data-route-fields]');if(route)route.hidden=external;row.querySelectorAll('[data-external-fields]').forEach(field=>field.hidden=!external);if(!external){const path=row.querySelector('[name="path"]');const label=row.querySelector('[name="label"]');if(path&&label&&(!path.value.trim()||path.value==='/uj-oldal'))path.value=`/${createSlug(label.value)}`;}}
function saveNavigationFromForm(event){const root=event.currentTarget.closest('.admin-page');const items=[...root.querySelectorAll('[data-nav-item]')].map((row,index)=>{const type=row.querySelector('[data-type]')?.value==='external'?'external':'route';const item={label:row.querySelector('[name="label"]')?.value.trim()||`Menüpont ${index+1}`,type,enabled:row.querySelector('[name="enabled"]')?.checked??true,order:index};if(type==='external'){item.url=row.querySelector('[name="url"]')?.value.trim()||'';item.urlKey=row.querySelector('[name="urlKey"]')?.value.trim()||'';}else item.path=row.querySelector('[name="path"]')?.value.trim()||`/${createSlug(item.label)}`||'/';return item;});const status=root.querySelector('[data-nav-save-status]');if(!saveNavigation(items)){if(status)status.textContent='Mentés sikertelen';return;}syncPagesFromNavigation(items);if(status)status.textContent='Mentve ✓';}
function moveItem(row,direction,root){const rows=[...root.querySelectorAll('[data-nav-item]')],index=rows.indexOf(row),target=rows[index+direction];if(!target)return;direction<0?target.before(row):target.after(row);[...root.querySelectorAll('[data-nav-item]')].forEach((item,i)=>{const n=item.querySelector('.admin-nav-number');if(n)n.textContent=`${i+1}.`;});}
function updateCount(root){const count=root.querySelector('[data-item-count]');if(count)count.textContent=root.querySelectorAll('[data-nav-item]').length;}
function normalizeItems(items){return[...items].map((item,index)=>({...item,enabled:item.enabled!==false,order:item.order??index})).sort((a,b)=>a.order-b.order);}
function renderItem(item,index){const external=item.type==='external';const url=external?String(item.url||''):'',urlKey=external?String(item.urlKey||''):'',path=external?'':String(item.path||`/${createSlug(item.label)}`);return `<article class="admin-nav-item" data-nav-item><div class="admin-nav-item-top"><strong class="admin-nav-number">${index+1}.</strong><label class="admin-form-field admin-nav-label"><span>Megnevezés</span><input name="label" value="${escapeHtml(item.label||'')}" maxlength="60"></label><label class="admin-form-field admin-nav-type"><span>Típus</span><select name="type" data-type><option value="route" ${!external?'selected':''}>Oldal</option><option value="external" ${external?'selected':''}>Külső link</option></select></label><label class="admin-switch"><input name="enabled" type="checkbox" ${item.enabled!==false?'checked':''}><span>Aktív</span></label></div><div class="admin-nav-fields"><label class="admin-form-field" data-route-fields ${external?'hidden':''}><span>Elérés</span><input name="path" value="${escapeHtml(path)}" placeholder="/bemutatkozas"></label><label class="admin-form-field" data-external-fields ${!external?'hidden':''}><span>Link / URL</span><input name="url" value="${escapeHtml(url)}" placeholder="https://pelda.hu"></label><label class="admin-form-field" data-external-fields ${!external?'hidden':''}><span>URL kulcs</span><input name="urlKey" value="${escapeHtml(urlKey)}" placeholder="pl. twitch"></label></div><div class="admin-nav-actions"><button class="button button-secondary" type="button" data-up>↑ Fel</button><button class="button button-secondary" type="button" data-down>↓ Le</button><button class="button button-secondary" type="button" data-delete>Törlés</button></div></article>`;}
function createSlug(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');}
function escapeHtml(value){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
