import { error, ok } from "../../core/response";
import { getAuthenticatedUser, hasRole } from "../../core/auth/require-auth";
import { normalizeEditorDocument } from "../../core/page-model";
import { validatePublishDocument } from "../../core/editor-validation";
import type { Env } from "../../types/env";

type PageRow={id:string;slug:string;title:string;description:string;content_json:string;is_published:number;published_revision_id:string|null;updated_at:string};
function parse(value:string):any{try{return JSON.parse(value)}catch{return {}}}
function canonical(document:any,pageId:string){const page=document?.pages?.[pageId];return Boolean(document&&document.type==='sanci-page-document'&&document.schemaVersion===1&&document.activePageId===pageId&&page?.id===pageId&&page.rootId&&page.nodes&&typeof page.nodes==='object')}
async function audit(env:Env,userId:string,action:string,pageId:string,metadata:unknown){await env.DB.prepare(`INSERT INTO audit_log (id,user_id,action,entity_type,entity_id,metadata_json) VALUES (?,?,?,?,?,?)`).bind(crypto.randomUUID(),userId,action,'page',pageId,JSON.stringify(metadata)).run()}
export async function adminEditorRoute(request:Request,env:Env):Promise<Response>{
 const user=await getAuthenticatedUser(request,env);if(!user)return error('UNAUTHORIZED',401,'Authentication required');if(!hasRole(user,'editor'))return error('FORBIDDEN',403,'Editor role required');
 const url=new URL(request.url),pageId=url.searchParams.get('pageId')||'';if(!pageId)return error('INVALID_PAGE_ID',400);
 if(request.method==='GET'){
  const row=await env.DB.prepare(`SELECT id,slug,title,description,content_json,is_published,published_revision_id,updated_at FROM pages WHERE id=? LIMIT 1`).bind(pageId).first<PageRow>();if(!row)return error('PAGE_NOT_FOUND',404);
  const document=normalizeEditorDocument(parse(row.content_json),row.id,row.title,row.slug,row.description);if(!document)return error('PAGE_NOT_MIGRATED',409,'Az oldal dokumentuma nem alakítható Editor v2 Page Modelre.');
  const revisions=await env.DB.prepare(`SELECT id,version,note,created_by,created_at FROM editor_revisions WHERE page_id=? ORDER BY version DESC LIMIT 30`).bind(pageId).all();return ok({page:{id:row.id,slug:row.slug,title:row.title,description:row.description,isPublished:Boolean(row.is_published),updatedAt:row.updated_at,publishedRevisionId:row.published_revision_id,document},revisions:revisions.results});
 }
 if(request.method==='POST'){
  let body:any;try{body=await request.json()}catch{return error('INVALID_JSON',400)}const id=typeof body.pageId==='string'?body.pageId:pageId;if(!id)return error('INVALID_PAGE_ID',400);
  const action=typeof body.action==='string'?body.action:'';if(action==='unpublish'){const current=await env.DB.prepare('SELECT is_published FROM pages WHERE id=? LIMIT 1').bind(id).first<{is_published:number}>();if(!current)return error('PAGE_NOT_FOUND',404);if(!current.is_published)return ok({pageId:id,published:false,changed:false});await env.DB.prepare('UPDATE pages SET is_published=0,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(id).run();await audit(env,user.id,'page.unpublish',id,{});return ok({pageId:id,published:false,changed:true,savedAt:new Date().toISOString()})}
  const document=body.document;if(!document||!canonical(document,id))return error('INVALID_EDITOR_DOCUMENT',400,'A mentett dokumentumnak az Editor v2 Page Modelt kell követnie.');
  const row=await env.DB.prepare('SELECT id FROM pages WHERE id=? LIMIT 1').bind(id).first<{id:string}>();if(!row)return error('PAGE_NOT_FOUND',404);
  const latest=await env.DB.prepare('SELECT COALESCE(MAX(version),0) AS version FROM editor_revisions WHERE page_id=?').bind(id).first<{version:number}>();const currentVersion=Number(latest?.version||0);const expectedVersion=body.expectedVersion===undefined?null:Number(body.expectedVersion);if(expectedVersion!==null&&(!Number.isInteger(expectedVersion)||expectedVersion!==currentVersion))return error('REVISION_CONFLICT',409,'Az oldal időközben módosult. Töltsd újra az oldalt a legfrissebb verzióval.');const version=currentVersion+1;const revId=crypto.randomUUID();const publish=body.publish===true;const note=typeof body.note==='string'?body.note.slice(0,200):publish?'Publikálás':'Editor mentés';const persistedDocument={...document,revision:version,pages:{...document.pages,[id]:{...document.pages[id],revision:version}}};const json=JSON.stringify(persistedDocument);if(json.length>180000)return error('DOCUMENT_TOO_LARGE',400);if(publish){const validationError=validatePublishDocument(document,id);if(validationError)return error(validationError,409,'A dokumentum publikálás előtt nem felel meg az Editor v2 Page Model ellenőrzésnek.')}
  const statements=[env.DB.prepare(`UPDATE pages SET content_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(json,id),env.DB.prepare(`INSERT INTO editor_revisions (id,page_id,version,document_json,created_by,note) VALUES (?,?,?,?,?,?)`).bind(revId,id,version,json,user.id,note)];if(publish)statements.push(env.DB.prepare(`UPDATE pages SET published_content_json=?,published_revision_id=?,is_published=1,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(json,revId,id));await env.DB.batch(statements);if(publish)await audit(env,user.id,'page.publish',id,{version,revisionId:revId});return ok({pageId:id,version,revisionId:revId,published:publish,savedAt:new Date().toISOString()});
 }
 if(request.method==='PUT'){
  let body:any;try{body=await request.json()}catch{return error('INVALID_JSON',400)}const id=typeof body.pageId==='string'?body.pageId:pageId;const version=Number(body.version);const expectedVersion=body.expectedVersion===undefined?null:Number(body.expectedVersion);if(!id||!Number.isInteger(version)||version<1)return error('INVALID_REVISION',400);const rev=await env.DB.prepare('SELECT document_json FROM editor_revisions WHERE page_id=? AND version=? LIMIT 1').bind(id,version).first<{document_json:string}>();if(!rev)return error('REVISION_NOT_FOUND',404);const document=normalizeEditorDocument(parse(rev.document_json),id);if(!document)return error('INVALID_REVISION',400,'A kiválasztott verzió nem Editor v2 dokumentum.');const latest=await env.DB.prepare('SELECT COALESCE(MAX(version),0) AS version FROM editor_revisions WHERE page_id=?').bind(id).first<{version:number}>();const currentVersion=Number(latest?.version||0);if(expectedVersion!==null&&(!Number.isInteger(expectedVersion)||expectedVersion!==currentVersion))return error('REVISION_CONFLICT',409,'Az oldal időközben módosult. Töltsd újra az oldalt a legfrissebb verzióval.');const next=currentVersion+1;const persistedDocument={...document,revision:next,pages:{...document.pages,[id]:{...document.pages[id],revision:next}}};const json=JSON.stringify(persistedDocument);const rollbackId=crypto.randomUUID();await env.DB.batch([env.DB.prepare('UPDATE pages SET content_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(json,id),env.DB.prepare(`INSERT INTO editor_revisions (id,page_id,version,document_json,created_by,note) VALUES (?,?,?,?,?,?)`).bind(rollbackId,id,next,json,user.id,`Rollback from v${version}`)]);await audit(env,user.id,'page.rollback',id,{version:next,revisionId:rollbackId,restoredFrom:version});return ok({pageId:id,version:next,revisionId:rollbackId,restoredFrom:version});
 }
 return error('METHOD_NOT_ALLOWED',405);
}
