import { error, ok } from "../../core/response";
import { getAuthenticatedUser, hasRole } from "../../core/auth/require-auth";
import { normalizeEditorDocument } from "../../core/page-model";
import type { Env } from "../../types/env";

type PageRow={id:string;slug:string;title:string;description:string;content_json:string;is_published:number;updated_at:string};
function parse(value:string):any{try{return JSON.parse(value)}catch{return {}}}
function canonical(document:any,pageId:string){const page=document?.pages?.[pageId];return Boolean(document&&document.type==='sanci-page-document'&&document.schemaVersion===1&&document.activePageId===pageId&&page?.id===pageId&&page.rootId&&page.nodes&&typeof page.nodes==='object')}
export function validatePublishDocument(document:any,pageId:string){if(!canonical(document,pageId))return 'INVALID_EDITOR_DOCUMENT';const page=document.pages[pageId];const nodes=page.nodes;const ids=Object.keys(nodes);if(!ids.length||!nodes[page.rootId])return 'INVALID_PAGE_ROOT';const seen=new Set<string>();for(const id of ids){if(seen.has(id))return 'DUPLICATE_NODE_ID';seen.add(id);const node=nodes[id];if(!node||node.id!==id)return 'INVALID_NODE';if(id===page.rootId){if(node.parentId!==null&&node.parentId!==undefined&&node.parentId!=='')return 'INVALID_ROOT_PARENT'}else{if(typeof node.parentId!=='string'||!nodes[node.parentId])return 'INVALID_NODE_PARENT';const parent=nodes[node.parentId];if(!Array.isArray(parent.children)||!parent.children.includes(id))return 'INVALID_PARENT_CHILD_LINK'}}for(const id of ids){const node=nodes[id];for(const childId of Array.isArray(node.children)?node.children:[]){if(!nodes[childId]||nodes[childId].parentId!==id)return 'INVALID_CHILD_LINK'}}const visited=new Set<string>();const walk=(id:string)=>{if(visited.has(id))return false;visited.add(id);const node=nodes[id];for(const childId of Array.isArray(node.children)?node.children:[]){if(!walk(childId))return false}return true};if(!walk(page.rootId)||visited.size!==ids.length)return 'INVALID_HIERARCHY';return null}
async function audit(env:Env,userId:string,action:string,pageId:string,metadata:unknown){await env.DB.prepare(`INSERT INTO audit_log (id,user_id,action,entity_type,entity_id,metadata_json) VALUES (?,?,?,?,?,?)`).bind(crypto.randomUUID(),userId,action,'page',pageId,JSON.stringify(metadata)).run()}
export async function adminEditorRoute(request:Request,env:Env):Promise<Response>{
 const user=await getAuthenticatedUser(request,env);if(!user)return error('UNAUTHORIZED',401,'Authentication required');if(!hasRole(user,'editor'))return error('FORBIDDEN',403,'Editor role required');
 const url=new URL(request.url),pageId=url.searchParams.get('pageId')||'';if(!pageId)return error('INVALID_PAGE_ID',400);
 if(request.method==='GET'){
  const row=await env.DB.prepare(`SELECT id,slug,title,description,content_json,is_published,updated_at FROM pages WHERE id=? LIMIT 1`).bind(pageId).first<PageRow>();if(!row)return error('PAGE_NOT_FOUND',404);
  const document=normalizeEditorDocument(parse(row.content_json),row.id,row.title,row.slug,row.description);if(!document)return error('PAGE_NOT_MIGRATED',409,'Az oldal dokumentuma nem alakítható Editor v2 Page Modelre.');
  const revisions=await env.DB.prepare(`SELECT id,version,note,created_by,created_at FROM editor_revisions WHERE page_id=? ORDER BY version DESC LIMIT 30`).bind(pageId).all();return ok({page:{id:row.id,slug:row.slug,title:row.title,description:row.description,isPublished:Boolean(row.is_published),updatedAt:row.updated_at,document},revisions:revisions.results});
 }
 if(request.method==='POST'){
  let body:any;try{body=await request.json()}catch{return error('INVALID_JSON',400)}const id=typeof body.pageId==='string'?body.pageId:pageId;if(!id)return error('INVALID_PAGE_ID',400);
  const action=typeof body.action==='string'?body.action:'';if(action==='unpublish'){const current=await env.DB.prepare('SELECT is_published FROM pages WHERE id=? LIMIT 1').bind(id).first<{is_published:number}>();if(!current)return error('PAGE_NOT_FOUND',404);if(!current.is_published)return ok({pageId:id,published:false,changed:false});await env.DB.prepare('UPDATE pages SET is_published=0,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(id).run();await audit(env,user.id,'page.unpublish',id,{});return ok({pageId:id,published:false,changed:true,savedAt:new Date().toISOString()})}
  const document=body.document;if(!document||!canonical(document,id))return error('INVALID_EDITOR_DOCUMENT',400,'A mentett dokumentumnak az Editor v2 Page Modelt kell követnie.');
  const row=await env.DB.prepare('SELECT id FROM pages WHERE id=? LIMIT 1').bind(id).first<{id:string}>();if(!row)return error('PAGE_NOT_FOUND',404);const json=JSON.stringify(document);if(json.length>180000)return error('DOCUMENT_TOO_LARGE',400);
  const latest=await env.DB.prepare('SELECT COALESCE(MAX(version),0) AS version FROM editor_revisions WHERE page_id=?').bind(id).first<{version:number}>();const version=Number(latest?.version||0)+1;const revId=crypto.randomUUID();const publish=body.publish===true;const note=typeof body.note==='string'?body.note.slice(0,200):publish?'Publikálás':'Editor mentés';if(publish){const validationError=validatePublishDocument(document,id);if(validationError)return error(validationError,409,'A dokumentum publikálás előtt nem felel meg az Editor v2 Page Model ellenőrzésnek.')}
  const statements=[env.DB.prepare(`UPDATE pages SET content_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(json,id),env.DB.prepare(`INSERT INTO editor_revisions (id,page_id,version,document_json,created_by,note) VALUES (?,?,?,?,?,?)`).bind(revId,id,version,json,user.id,note)];if(publish)statements.push(env.DB.prepare(`UPDATE pages SET published_content_json=?,is_published=1,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(json,id));await env.DB.batch(statements);if(publish)await audit(env,user.id,'page.publish',id,{version,revisionId:revId});return ok({pageId:id,version,revisionId:revId,published:publish,savedAt:new Date().toISOString()});
 }
 if(request.method==='PUT'){
  let body:any;try{body=await request.json()}catch{return error('INVALID_JSON',400)}const id=typeof body.pageId==='string'?body.pageId:pageId;const version=Number(body.version);if(!id||!Number.isInteger(version)||version<1)return error('INVALID_REVISION',400);const rev=await env.DB.prepare('SELECT document_json FROM editor_revisions WHERE page_id=? AND version=? LIMIT 1').bind(id,version).first<{document_json:string}>();if(!rev)return error('REVISION_NOT_FOUND',404);const document=normalizeEditorDocument(parse(rev.document_json),id);if(!document)return error('INVALID_REVISION',400,'A kiválasztott verzió nem Editor v2 dokumentum.');const latest=await env.DB.prepare('SELECT COALESCE(MAX(version),0) AS version FROM editor_revisions WHERE page_id=?').bind(id).first<{version:number}>();const next=Number(latest?.version||0)+1;const json=JSON.stringify(document);await env.DB.batch([env.DB.prepare('UPDATE pages SET content_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(json,id),env.DB.prepare(`INSERT INTO editor_revisions (id,page_id,version,document_json,created_by,note) VALUES (?,?,?,?,?,?)`).bind(crypto.randomUUID(),id,next,json,user.id,`Rollback from v${version}`)]);return ok({pageId:id,version:next,restoredFrom:version});
 }
 return error('METHOD_NOT_ALLOWED',405);
}
