import { error, ok } from "../../core/response";
import { getAuthenticatedUser, hasRole } from "../../core/auth/require-auth";
import { normalizeEditorDocument } from "../../core/page-model";
import type { Env } from "../../types/env";

type PageRow={id:string;slug:string;title:string;description:string;content_json:string;is_published:number;published_revision_id:string|null;sort_order:number;created_at:string;updated_at:string};
type PageBody={id?:unknown;slug?:unknown;title?:unknown;description?:unknown;document?:unknown;isPublished?:unknown;sortOrder?:unknown;expectedVersion?:unknown};
function parse(value:string):any{try{return JSON.parse(value)}catch{return {}}}
function canonical(value:unknown,id:string):boolean{const d:any=value;const p=d?.pages?.[id];return Boolean(d&&d.type==='sanci-page-document'&&d.schemaVersion===1&&d.activePageId===id&&p&&p.id===id&&p.rootId&&p.nodes&&typeof p.nodes==='object')}
function serialize(row:PageRow,includeContent=true){const raw=parse(row.content_json);const document=normalizeEditorDocument(raw,row.id,row.title,row.slug,row.description);return{id:row.id,slug:row.slug,title:row.title,description:row.description,sortOrder:row.sort_order,revision:document?.revision??0,...(includeContent?{content:document||raw}:{}),isPublished:Boolean(row.is_published),publishedRevisionId:row.published_revision_id??null,createdAt:row.created_at,updatedAt:row.updated_at}}
function validSlug(value:string){return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value)}
async function audit(env:Env,userId:string,action:string,id:string,metadata:unknown){await env.DB.prepare('INSERT INTO audit_log (id,user_id,action,entity_type,entity_id,metadata_json) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),userId,action,"page",id,JSON.stringify(metadata)).run()}
export async function adminPagesRoute(request:Request,env:Env):Promise<Response>{
 const user=await getAuthenticatedUser(request,env);if(!user)return error('UNAUTHORIZED',401,'Authentication required');if(!hasRole(user,'editor'))return error('FORBIDDEN',403,'Editor role required');
 if(request.method==='GET'){const metaOnly=new URL(request.url).searchParams.get('meta')==='1';const rows=await env.DB.prepare('SELECT id,slug,title,description,content_json,is_published,published_revision_id,sort_order,created_at,updated_at FROM pages ORDER BY sort_order ASC').all<PageRow>();return ok(rows.results.map(r=>serialize(r,!metaOnly)))}
 let body:PageBody;try{body=await request.json() as PageBody}catch{return error('INVALID_JSON',400)}
 if(request.method==='DELETE'){const id=typeof body.id==='string'?body.id:'';if(!id)return error('INVALID_PAGE_ID',400);const count=await env.DB.prepare('SELECT COUNT(*) AS count FROM pages').first<{count:number}>();if(Number(count?.count||0)<=1)return error('LAST_PAGE',409,'Az utolsó oldal nem törölhető.');const existingOrder=await env.DB.prepare('SELECT sort_order FROM pages WHERE id=? LIMIT 1').bind(id).first<{sort_order:number}>();const result=await env.DB.prepare('DELETE FROM pages WHERE id=?').bind(id).run();if(!result.meta.changes)return error('PAGE_NOT_FOUND',404);if(existingOrder){await env.DB.prepare('UPDATE pages SET sort_order=sort_order-1 WHERE sort_order>?').bind(existingOrder.sort_order).run()}await audit(env,user.id,'page.delete',id,{});return ok({id,deleted:true})}
 if(request.method==='PATCH'){
  const id=typeof body.id==='string'?body.id:'';const requestedOrder=typeof body.sortOrder==='number'?Math.floor(body.sortOrder):null;const title=typeof body.title==='string'?body.title.trim():'';const requestedSlug=typeof body.slug==='string'?body.slug.trim().toLowerCase():'';const requestedDescription=typeof body.description==='string'?body.description.trim():null;
  if(!id)return error('INVALID_PAGE_ID',400);if(requestedOrder!==null&&requestedOrder<0)return error('INVALID_PAGE_ORDER',400);if(title&&title.length>160)return error('INVALID_PAGE_TITLE',400);if(requestedSlug&&(!validSlug(requestedSlug)||requestedSlug.length>80))return error('INVALID_PAGE_SLUG',400,'A slug csak kisbetűs betűket, számokat és kötőjeleket tartalmazhat.');if(requestedDescription!==null&&requestedDescription.length>500)return error('INVALID_PAGE_DESCRIPTION',400);if(!title&&!requestedSlug&&requestedDescription===null&&requestedOrder===null)return error('INVALID_PAGE_UPDATE',400);
  const existing=await env.DB.prepare('SELECT id,slug,title,description,content_json,is_published,published_revision_id,sort_order,created_at,updated_at FROM pages WHERE id=? LIMIT 1').bind(id).first<PageRow>();if(!existing)return error('PAGE_NOT_FOUND',404);
  const nextTitle=title||existing.title;const nextSlug=requestedSlug||existing.slug;const nextDescription=requestedDescription===null?existing.description:requestedDescription;const nextOrder=requestedOrder===null?existing.sort_order:requestedOrder;
  const latest=await env.DB.prepare('SELECT COALESCE(MAX(version),0) AS version FROM editor_revisions WHERE page_id=?').bind(id).first<{version:number}>();const currentVersion=Number(latest?.version||0);const expectedVersion=body.expectedVersion===undefined?null:Number(body.expectedVersion);if(expectedVersion!==null&&(!Number.isInteger(expectedVersion)||expectedVersion!==currentVersion))return error('REVISION_CONFLICT',409,'Az oldal időközben módosult. Töltsd újra az oldalt a legfrissebb verzióval.');
  const document=normalizeEditorDocument(parse(existing.content_json),id,existing.title,existing.slug,existing.description);if(!document)return error('PAGE_NOT_CANONICAL',409,'Az oldal dokumentuma nem canonical Editor v2 Page Model.');
  const page=document.pages[id];page.name=nextTitle;page.slug=nextSlug;page.metadata={...(page.metadata||{}),title:nextTitle,description:nextDescription};
  const contentChanged=nextTitle!==existing.title||nextSlug!==existing.slug||nextDescription!==existing.description;const revisionId=contentChanged?crypto.randomUUID():null;const nextVersion=contentChanged?currentVersion+1:currentVersion;const persistedDocument=contentChanged?{...document,revision:nextVersion}:document;const contentJson=contentChanged?JSON.stringify(persistedDocument):existing.content_json;if(contentJson.length>180000)return error('PAGE_TOO_LARGE',400);
  try{
   const statements:any[]=[];
   if(requestedOrder!==null&&requestedOrder!==existing.sort_order){const movingUp=requestedOrder<existing.sort_order;const neighbor=await env.DB.prepare(movingUp?'SELECT id,sort_order FROM pages WHERE sort_order<? ORDER BY sort_order DESC LIMIT 1':'SELECT id,sort_order FROM pages WHERE sort_order>? ORDER BY sort_order ASC LIMIT 1').bind(existing.sort_order).first<{id:string;sort_order:number}>();if(neighbor){statements.push(env.DB.prepare('UPDATE pages SET sort_order=? WHERE id=?').bind(existing.sort_order,neighbor.id));statements.push(env.DB.prepare('UPDATE pages SET sort_order=? WHERE id=?').bind(neighbor.sort_order,id))}}
   statements.push(env.DB.prepare('UPDATE pages SET title=?,slug=?,description=?,content_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(nextTitle,nextSlug,nextDescription,contentJson,id));
   if(contentChanged)statements.push(env.DB.prepare('INSERT INTO editor_revisions (id,page_id,version,document_json,created_by,note) VALUES (?,?,?,?,?,?)').bind(revisionId,id,nextVersion,contentJson,user.id,'Oldal metaadat módosítás'));
   if(contentChanged&&existing.is_published)statements.push(env.DB.prepare('UPDATE pages SET published_content_json=?,published_revision_id=? WHERE id=?').bind(contentJson,revisionId,id));
   await env.DB.batch(statements);
  }catch(e){if(String(e).toLowerCase().includes('unique'))return error('SLUG_EXISTS',409,'Slug already exists');throw e}
  await audit(env,user.id,'page.update',id,{oldTitle:existing.title,title:nextTitle,oldSlug:existing.slug,slug:nextSlug,oldDescription:existing.description,description:nextDescription,version:contentChanged?nextVersion:null,revisionId});return ok(serialize({...existing,title:nextTitle,slug:nextSlug,description:nextDescription,sort_order:nextOrder,content_json:contentJson,published_revision_id:existing.is_published&&contentChanged?revisionId:existing.published_revision_id},true))
 }
 if(request.method!=='POST')return error('METHOD_NOT_ALLOWED',405);
 const title=typeof body.title==='string'?body.title.trim():'';const slug=typeof body.slug==='string'?body.slug.trim().toLowerCase():'';const description=typeof body.description==='string'?body.description.trim():'';const id=typeof body.id==='string'?body.id.trim():crypto.randomUUID();const document=body.document;
 if(!title||title.length>160||!validSlug(slug)||slug.length>80||description.length>500)return error('INVALID_PAGE',400);if(!canonical(document,id))return error('INVALID_EDITOR_DOCUMENT',400,'Az új oldalnak Editor v2 Page Model dokumentumot kell tartalmaznia.');
 let contentJson:string;try{contentJson=JSON.stringify(document);if(contentJson.length>180000)return error('PAGE_TOO_LARGE',400)}catch{return error('INVALID_CONTENT',400)}
 const isPublished=body.isPublished===true;const revisionId=crypto.randomUUID();const initialDocument={...document,revision:1};const initialJson=JSON.stringify(initialDocument);const nextOrder=(await env.DB.prepare('SELECT COALESCE(MAX(sort_order),-1)+1 AS next FROM pages').first<{next:number}>())?.next??0;
 try{await env.DB.batch([env.DB.prepare('INSERT INTO pages (id,slug,title,description,content_json,published_content_json,published_revision_id,is_published,sort_order,updated_at) VALUES (?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)').bind(id,slug,title,description,initialJson,isPublished?initialJson:null,isPublished?revisionId:null,isPublished?1:0,nextOrder),env.DB.prepare('INSERT INTO editor_revisions (id,page_id,version,document_json,created_by,note) VALUES (?,?,?,?,?,?)').bind(revisionId,id,1,initialJson,user.id,'Oldal létrehozva az Editor v2-ben'))])}catch(e){if(String(e).toLowerCase().includes('unique'))return error('SLUG_EXISTS',409,'Slug already exists');throw e}
 await audit(env,user.id,'page.create',id,{slug,title,revisionId});return ok({id,slug,title,description,content:initialDocument,isPublished,version:1,revisionId});
}