import { error, ok } from "../../core/response";
import { getAuthenticatedUser, hasRole } from "../../core/auth/require-auth";
import { normalizeEditorDocument } from "../../core/page-model";
import type { Env } from "../../types/env";

type PageRow={id:string;slug:string;title:string;description:string;content_json:string;is_published:number;created_at:string;updated_at:string};
type PageBody={id?:unknown;slug?:unknown;title?:unknown;description?:unknown;document?:unknown;isPublished?:unknown};
function parse(value:string):any{try{return JSON.parse(value)}catch{return {}}}
function canonical(value:unknown,id:string):boolean{const d:any=value;const p=d?.pages?.[id];return Boolean(d&&d.type==='sanci-page-document'&&d.schemaVersion===1&&d.activePageId===id&&p&&p.id===id&&p.rootId&&p.nodes&&typeof p.nodes==='object')}
function serialize(row:PageRow,includeContent=true){const raw=parse(row.content_json);const document=normalizeEditorDocument(raw,row.id,row.title,row.slug,row.description);return{id:row.id,slug:row.slug,title:row.title,description:row.description,...(includeContent?{content:document||raw}:{}),isPublished:Boolean(row.is_published),createdAt:row.created_at,updatedAt:row.updated_at}}
function validSlug(value:string){return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value)}
async function audit(env:Env,userId:string,action:string,id:string,metadata:unknown){await env.DB.prepare(`INSERT INTO audit_log (id,user_id,action,entity_type,entity_id,metadata_json) VALUES (?,?,?,?,?,?)`).bind(crypto.randomUUID(),userId,action,"page",id,JSON.stringify(metadata)).run()}
export async function adminPagesRoute(request:Request,env:Env):Promise<Response>{
 const user=await getAuthenticatedUser(request,env);if(!user)return error('UNAUTHORIZED',401,'Authentication required');if(!hasRole(user,'editor'))return error('FORBIDDEN',403,'Editor role required');
 if(request.method==='GET'){const metaOnly=new URL(request.url).searchParams.get('meta')==='1';const rows=await env.DB.prepare(`SELECT id,slug,title,description,content_json,is_published,created_at,updated_at FROM pages ORDER BY updated_at DESC,title ASC`).all<PageRow>();return ok(rows.results.map(r=>serialize(r,!metaOnly)))}
 let body:PageBody;try{body=await request.json() as PageBody}catch{return error('INVALID_JSON',400)}
 if(request.method==='DELETE'){const id=typeof body.id==='string'?body.id:'';if(!id)return error('INVALID_PAGE_ID',400);const count=await env.DB.prepare(`SELECT COUNT(*) AS count FROM pages`).first<{count:number}>();if(Number(count?.count||0)<=1)return error('LAST_PAGE',409,'Az utolsó oldal nem törölhető.');const result=await env.DB.prepare('DELETE FROM pages WHERE id=?').bind(id).run();if(!result.meta.changes)return error('PAGE_NOT_FOUND',404);await audit(env,user.id,'page.delete',id,{});return ok({id,deleted:true})}
 if(request.method==='PATCH'){const id=typeof body.id==='string'?body.id:'';const title=typeof body.title==='string'?body.title.trim():'';const requestedSlug=typeof body.slug==='string'?body.slug.trim().toLowerCase():'';if(!id)return error('INVALID_PAGE_ID',400);if(title&&title.length>160)return error('INVALID_PAGE_TITLE',400);if(requestedSlug&&(!validSlug(requestedSlug)||requestedSlug.length>80))return error('INVALID_PAGE_SLUG',400,'A slug csak kisbetűs betűket, számokat és kötőjeleket tartalmazhat.');if(!title&&!requestedSlug)return error('INVALID_PAGE_UPDATE',400);const existing=await env.DB.prepare('SELECT id,slug,title,description,content_json,is_published,created_at,updated_at FROM pages WHERE id=? LIMIT 1').bind(id).first<PageRow>();if(!existing)return error('PAGE_NOT_FOUND',404);const nextTitle=title||existing.title;const nextSlug=requestedSlug||existing.slug;const document=normalizeEditorDocument(parse(existing.content_json),id,existing.title,existing.slug,existing.description);if(!document)return error('PAGE_NOT_CANONICAL',409,'Az oldal dokumentuma nem canonical Editor v2 Page Model.');const page=document.pages[id];page.name=nextTitle;page.slug=nextSlug;page.metadata={...(page.metadata||{}),title:nextTitle,description:existing.description||''};const contentJson=JSON.stringify(document);if(contentJson.length>180000)return error('PAGE_TOO_LARGE',400);try{await env.DB.prepare('UPDATE pages SET title=?,slug=?,content_json=?,published_content_json=CASE WHEN is_published=1 THEN ? ELSE published_content_json END,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(nextTitle,nextSlug,contentJson,contentJson,id).run()}catch(e){if(String(e).toLowerCase().includes('unique'))return error('SLUG_EXISTS',409,'Slug already exists');throw e}await audit(env,user.id,'page.update',id,{oldTitle:existing.title,title:nextTitle,oldSlug:existing.slug,slug:nextSlug});return ok(serialize({...existing,title:nextTitle,slug:nextSlug,content_json:contentJson},true))}
 if(request.method!=='POST')return error('METHOD_NOT_ALLOWED',405);
 const title=typeof body.title==='string'?body.title.trim():'';const slug=typeof body.slug==='string'?body.slug.trim().toLowerCase():'';const description=typeof body.description==='string'?body.description.trim():'';const id=typeof body.id==='string'?body.id.trim():crypto.randomUUID();const document=body.document;
 if(!title||title.length>160||!validSlug(slug)||slug.length>80||description.length>500)return error('INVALID_PAGE',400);
 if(!canonical(document,id))return error('INVALID_EDITOR_DOCUMENT',400,'Az új oldalnak Editor v2 Page Model dokumentumot kell tartalmaznia.');
 let contentJson:string;try{contentJson=JSON.stringify(document);if(contentJson.length>180000)return error('PAGE_TOO_LARGE',400)}catch{return error('INVALID_CONTENT',400)}
 const isPublished=body.isPublished===true;
 try{await env.DB.prepare(`INSERT INTO pages (id,slug,title,description,content_json,published_content_json,is_published,updated_at) VALUES (?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).bind(id,slug,title,description,contentJson,isPublished?contentJson:null,isPublished?1:0).run()}catch(e){if(String(e).toLowerCase().includes('unique'))return error('SLUG_EXISTS',409,'Slug already exists');throw e}
 await env.DB.prepare(`INSERT INTO editor_revisions (id,page_id,version,document_json,created_by,note) VALUES (?,?,?,?,?,?)`).bind(crypto.randomUUID(),id,1,contentJson,user.id,'Oldal létrehozva az Editor v2-ben').run();await audit(env,user.id,'page.create',id,{slug,title});return ok({id,slug,title,description,content:document,isPublished,version:1});
}
